export const accountConstants = {
    REGISTER_REQUEST: 'ACCOUNT_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'ACCOUNT_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'ACCOUNT_REGISTER_FAILURE',

    LOGIN_REQUEST: 'ACCOUNT_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'ACCOUNT_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'ACCOUNT_LOGIN_FAILURE',

    LOGOUT: 'ACCOUNT_LOGOUT',

    GETACCOUNT_REQUEST: 'ACCOUNT_GETACCOUNT_REQUEST',
    GETACCOUNT_SUCCESS: 'ACCOUNT_GETACCOUNT_SUCCESS',
    GETACCOUNT_FAILURE: 'ACCOUNT_GETACCOUNT_FAILURE'
}