export const accountConstants = {
    REGISTER_REQUEST: 'ACCOUNT_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'ACCOUNT_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'ACCOUNT_REGISTER_FAILURE',

    LOGIN_REQUEST: 'ACCOUNT_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'ACCOUNT_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'ACCOUNT_LOGIN_FAILURE',

    LOGOUT: 'ACCOUNT_LOGOUT',

    GETALL_REQUEST: 'ACCOUNT_GETALL_REQUEST',
    GETALL_SUCCESS: 'ACCOUNT_GETALL_SUCCESS',
    GETALL_FAILURE: 'ACCOUNT_GETALL_FAILURE'
}